version: '3.8'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    env_file:
      - ../.env

  app:
    build: ../
    restart: always
    volumes:
      - ..:/restful_users
    depends_on:
      - mongodb
    env_file:
      - ../.env
    ports:
      - '8000:8000'

volumes:
  mongodb-data:
